# Generated by Django 5.2.7 on 2025-11-23 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_create', 'Can create book'), ('can_delete', 'Can delete book'))},
        ),
    ]
