"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a%6-hd36nz4p))ztli^_35cy7j+rr(_*m(a!s1kf-t)e8^z25q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# For local development allow localhost and 127.0.0.1. In production set
# `DEBUG = False` and configure `ALLOWED_HOSTS` to your domain names.
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf',
    'relationship_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# SECURITY NOTE: DEBUG should be False in production. For local development
# we keep DEBUG = True above. Make sure to set DEBUG = False and configure
# `ALLOWED_HOSTS` before deploying to production.

# ---------------- Security Headers ---------------- #

# Protects against Cross-Site Scripting attacks
SECURE_BROWSER_XSS_FILTER = True

# Prevents the site from being rendered in iframes (clickjacking protection)
X_FRAME_OPTIONS = "DENY"

# Prevents MIME-type sniffing
SECURE_CONTENT_TYPE_NOSNIFF = True

# Ensures cookies only sent via HTTPS
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# Recommended: secure referrer policy
SECURE_REFERRER_POLICY = "same-origin"

# ---------------- Optional CSP (also step 4) ---------------- #
# Only used if django-csp is installed; otherwise set manually in middleware.
# Example:
# CSP_DEFAULT_SRC = ("'self'",)
MIDDLEWARE += [
    "LibraryProject.middleware.CSPMiddleware",
]

# settings.py

AUTH_USER_MODEL = 'relationship_app.User'

# Media files (for ImageField)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ---------------- HTTPS / HSTS Settings ---------------- #
# The following settings should be enabled in production when your site is
# served over HTTPS (with a valid SSL/TLS certificate). They are configurable
# via environment variables so deployments can toggle them without changing
# source code.


def _env_bool(name, default=False):
    """Return boolean from environment variables. Treats '1', 'true', 'yes'
    (case-insensitive) as True."""
    v = os.environ.get(name)
    if v is None:
        return default
    return str(v).lower() in ("1", "true", "yes")


# Redirect all HTTP requests to HTTPS. Enable in production by setting
# `DJANGO_SECURE_SSL_REDIRECT=1` in environment.
SECURE_SSL_REDIRECT = _env_bool("DJANGO_SECURE_SSL_REDIRECT", False)

# HTTP Strict Transport Security (HSTS) settings. Configure these in
# production. Example: `DJANGO_SECURE_HSTS_SECONDS=31536000` to set 1 year.
# WARNING: Enabling HSTS with a large value is irreversible for browsers that
# cache the directive — be careful and test with a low value first.
try:
    SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_SECURE_HSTS_SECONDS", "0"))
except ValueError:
    SECURE_HSTS_SECONDS = 0

SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", False)
SECURE_HSTS_PRELOAD = _env_bool("DJANGO_SECURE_HSTS_PRELOAD", False)

# Ensure cookies are only sent over HTTPS. Keep True in production.
SESSION_COOKIE_SECURE = _env_bool("DJANGO_SESSION_COOKIE_SECURE", True)
CSRF_COOKIE_SECURE = _env_bool("DJANGO_CSRF_COOKIE_SECURE", True)

# If you're behind a reverse proxy that terminates SSL (eg. Nginx), set this
# to let Django know the original request was HTTPS. Example in environment:
# DJANGO_SECURE_PROXY_SSL_HEADER=HTTP_X_FORWARDED_PROTO
SECURE_PROXY_SSL_HEADER = None
_proxy_header = os.environ.get("DJANGO_SECURE_PROXY_SSL_HEADER")
if _proxy_header:
    # expects header name only; Django expects a tuple of (header, value)
    SECURE_PROXY_SSL_HEADER = (_proxy_header, 'https')

# Note for deployment:
# - Use environment-specific configuration to avoid enabling strict
#   production settings while developing locally.